name: Django_app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install poetry
        poetry install

    - name: Lint with flake8
      run: |
        make lint

    - name: Run migrations
      env:
        DATABASE_URL: postgres://postgres:pass@localhost:5432/test_db
      run: |
        poetry run python manage.py migrate

    - name: Test with pytest
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        DATABASE_URL: postgres://postgres:pass@localhost:5432/test_db
      run: |
        make test

    - name: Publish code coverage
      uses: paambaati/codeclimate-action@v5.0.0
      if: github.ref_name == 'main'
      env:
        SECRET_KEY: ${{secrets.SECRET_KEY}}
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: make test-coverage
        debug: true
